name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente
  workflow_dispatch: # Permite acionar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: PGabrielClue # Substitua pelo SEU username
          svg_out_path: output/github-contribution-grid-snake.svg
          
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update snake animation"
          git push
