name: Snake Generator
on:
  workflow_dispatch:  # Permite executar manualmente
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: PGabrielClue  # 👈 SEU USERNAME AQUI
          svg_out_path: output/github-contribution-grid-snake.svg
          
      - name: Upload SVG
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: output/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update snake animation [skip ci]"
          git push
