name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:      # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: PGabrielClue  # 🔄 Substitua pelo SEU username
          svg_out_path: output/github-contribution-grid-snake.svg
      - name: Push SVG
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push
